export type DamageType='physical'|'magical'|'true';
export type Ability={name:string;tu:number;target:'foe'|'all-foes'|'self'|'all-allies'|'battlefield';power?:number;damageType?:DamageType;effect:string;status?:string};
export type Creature={id:string;name:string;stage:number;next?:string;level:number;hp:number;maxHp:number;atk:number;def:number;magic:number;speed:number;affinity:string;role:string;asset:string;xpYield:number;captureRate:number;abilities:Ability[]};
export type Zone={id:string;name:string;biome:string;x:number;y:number;danger:number;neighbors:string[];subsections:string[];encounters:string[];boss?:string;environmentAsset:string};
export type Item={id:string;name:string;kind:'capture'|'heal'|'buff';power:number;description:string};
export type FormationBonus={name:string;requires:string[];effect:string};

export const assetCatalog={
 divine:'/assets/creatures/divine.png',seraphic:'/assets/creatures/seraphic.png',empyrean:'/assets/creatures/empyrean.png',
 moon:'/assets/creatures/moon-sovereign.png',sun:'/assets/creatures/sun-sovereign.png',nocturne:'/assets/creatures/nocturne.png',infernus:'/assets/creatures/infernus.png',
 world:'/assets/world/world-map.png',town:'/assets/world/starter-town.png',forest:'/assets/world/forest-path.png',mountain:'/assets/world/mountain-pass.png',ruins:'/assets/world/ancient-ruins.png',volcanic:'/assets/world/volcanic-wastes.png',celestial:'/assets/world/celestial-peak.png'
} as const;

export const creatures:Creature[]=[
{id:'divine',name:'Divine',stage:1,next:'seraphic',level:12,hp:920,maxHp:920,atk:122,def:135,magic:188,speed:106,affinity:'Radiance',role:'Celestial',asset:assetCatalog.divine,xpYield:130,captureRate:.08,abilities:[{name:'Holy',tu:160,target:'foe',power:1950,damageType:'magical',effect:'1758–2149 magical damage.'},{name:'Immunity',tu:0,target:'self',effect:'Passive: immune to all negative status effects.',status:'immune'},{name:'Judgement',tu:250,target:'all-foes',power:1135,damageType:'magical',effect:'1024–1251 magical damage to all foes.'},{name:'Justice',tu:100,target:'foe',power:1170,damageType:'physical',effect:'1056–1291 physical damage; +100% vs Demonic foes.'},{name:'Neutralize',tu:130,target:'all-foes',effect:'Removes all positive and negative effects from targets.',status:'dispel'}]},
{id:'seraphic',name:'Seraphic',stage:2,next:'empyrean',level:32,hp:1760,maxHp:1760,atk:205,def:238,magic:340,speed:118,affinity:'Radiance',role:'Seraph',asset:assetCatalog.seraphic,xpYield:340,captureRate:.035,abilities:[{name:'Sacred Lance',tu:150,target:'foe',power:2450,damageType:'magical',effect:'2200–2700 magical damage; ignores 25% magical defense.'},{name:'Seraphic Grace',tu:0,target:'self',effect:'Passive: survive one lethal attack at 1 HP.',status:'last-stand'},{name:'Divine Decree',tu:240,target:'all-foes',power:1500,damageType:'magical',effect:'1350–1650 magical damage and removes one boon.'},{name:'Retribution',tu:120,target:'foe',power:1680,damageType:'physical',effect:'+100% vs Demonic; +50% if the foe damaged an ally.'},{name:'Sanctification',tu:170,target:'all-allies',effect:'Cleanse allies and grant status immunity for 100 TU.',status:'sanctified'}]},
{id:'empyrean',name:'Empyrean',stage:3,level:60,hp:3250,maxHp:3250,atk:350,def:410,magic:590,speed:126,affinity:'Radiance',role:'Empyrean',asset:assetCatalog.empyrean,xpYield:900,captureRate:.01,abilities:[{name:'Heavenfall',tu:180,target:'foe',power:3350,damageType:'magical',effect:'3000–3700 magical damage; +50% below 25% HP.'},{name:'Perfect Divinity',tu:0,target:'self',effect:'Passive: immune to debuffs; boons cannot be removed.',status:'perfect-divinity'},{name:'Final Judgement',tu:300,target:'all-foes',power:2000,damageType:'magical',effect:'1800–2200 magical damage; strips all boons; +100% vs Demonic.'},{name:'Divine Intervention',tu:200,target:'all-allies',effect:'Cleanse, restore 20% max HP, and grant 100 TU immunity.',status:'intervention'},{name:'Absolute Authority',tu:250,target:'battlefield',effect:'For 150 TU enemies cannot gain boons and allies cannot receive debuffs.',status:'authority'}]},
{id:'sun',name:'Sun Sovereign',stage:1,level:45,hp:2800,maxHp:2800,atk:405,def:330,magic:440,speed:92,affinity:'Solar',role:'Sacred Beast',asset:assetCatalog.sun,xpYield:780,captureRate:.015,abilities:[{name:'Solar Roar',tu:180,target:'all-foes',power:1750,damageType:'magical',effect:'Solar damage to all foes.'},{name:'Crown of Day',tu:140,target:'all-allies',effect:'Raise allied attack and magic for 120 TU.',status:'solar-crown'},{name:'Zenith',tu:260,target:'foe',power:3600,damageType:'true',effect:'True solar damage that ignores defense.'}]},
{id:'moon',name:'Moon Sovereign',stage:1,level:45,hp:2400,maxHp:2400,atk:310,def:350,magic:505,speed:130,affinity:'Lunar',role:'Sacred Beast',asset:assetCatalog.moon,xpYield:780,captureRate:.015,abilities:[{name:'Eclipse',tu:190,target:'all-foes',power:1600,damageType:'magical',effect:'Lunar damage and delays enemy actions.'},{name:'Tidal Veil',tu:130,target:'all-allies',effect:'Raise evasion and magic defense for 100 TU.',status:'veil'},{name:'Nightfall',tu:240,target:'foe',power:3200,damageType:'magical',effect:'Heavy lunar damage; stronger against buffed foes.'}]},
{id:'nocturne',name:'Nocturne',stage:1,level:18,hp:1050,maxHp:1050,atk:190,def:112,magic:240,speed:160,affinity:'Shadow',role:'Assassin',asset:assetCatalog.nocturne,xpYield:165,captureRate:.22,abilities:[{name:'Crescent Cut',tu:90,target:'foe',power:850,damageType:'physical',effect:'Fast physical strike.'},{name:'Fade',tu:80,target:'self',effect:'Gain evasion for 80 TU.',status:'evasion'},{name:'Soul Rend',tu:150,target:'foe',power:1250,damageType:'magical',effect:'Shadow damage and reduces defense.',status:'shredded'}]},
{id:'infernus',name:'Infernus Horde',stage:1,level:28,hp:2200,maxHp:2200,atk:330,def:245,magic:185,speed:94,affinity:'Infernal',role:'Demonic',asset:assetCatalog.infernus,xpYield:300,captureRate:.1,abilities:[{name:'Maul',tu:120,target:'foe',power:1300,damageType:'physical',effect:'Heavy physical damage.'},{name:'Hellrush',tu:180,target:'all-foes',power:900,damageType:'physical',effect:'Charges the entire enemy line.'},{name:'Blood Frenzy',tu:100,target:'self',effect:'Raise attack while lowering defense.',status:'frenzy'}]},
{id:'rift-drake',name:'Rift Drake',stage:1,next:'rift-tyrant',level:14,hp:1450,maxHp:1450,atk:170,def:150,magic:125,speed:102,affinity:'Void',role:'Beast',asset:assetCatalog.infernus,xpYield:120,captureRate:.3,abilities:[{name:'Rift Bite',tu:120,target:'foe',power:700,damageType:'physical',effect:'Void-infused bite.'},{name:'Warp Howl',tu:160,target:'all-foes',power:450,damageType:'magical',effect:'Minor damage and action delay.'}]},
{id:'rift-tyrant',name:'Rift Tyrant',stage:2,level:34,hp:2900,maxHp:2900,atk:345,def:280,magic:250,speed:110,affinity:'Void',role:'Beast',asset:assetCatalog.infernus,xpYield:380,captureRate:.12,abilities:[{name:'Abyssal Crush',tu:170,target:'foe',power:1800,damageType:'physical',effect:'Massive physical hit.'},{name:'Riftstorm',tu:240,target:'all-foes',power:1100,damageType:'magical',effect:'Void damage to all foes.'}]}
];

export const zones:Zone[]=[
{id:'dawnreach',name:'Dawnreach Coast',biome:'Town/Coast',x:14,y:70,danger:1,neighbors:['verdant'],subsections:['Harbor','Old Road','Starter Town'],encounters:['rift-drake'],environmentAsset:assetCatalog.town},
{id:'verdant',name:'Verdant March',biome:'Forest',x:27,y:61,danger:2,neighbors:['dawnreach','ashen','crown'],subsections:['Forest Path','Moss Clearing','Rootbridge','Deep Grove'],encounters:['nocturne','rift-drake'],environmentAsset:assetCatalog.forest},
{id:'ashen',name:'Ashen Steps',biome:'Volcanic',x:43,y:69,danger:4,neighbors:['verdant','crown','hollow'],subsections:['Cinder Road','Lava Shelf','Ash Gate'],encounters:['infernus','rift-tyrant'],environmentAsset:assetCatalog.volcanic},
{id:'crown',name:'Crown Basin',biome:'Mountain',x:47,y:48,danger:3,neighbors:['verdant','ashen','moonfen','hollow'],subsections:['Mountain Pass','Wind Shelf','Crown Camp'],encounters:['rift-drake','nocturne'],environmentAsset:assetCatalog.mountain},
{id:'moonfen',name:'Moonfen',biome:'Lunar Swamp',x:64,y:42,danger:5,neighbors:['crown','starfall'],subsections:['Silver Mire','Flooded Shrine','Moon Pool'],encounters:['nocturne','moon'],boss:'moon',environmentAsset:assetCatalog.ruins},
{id:'hollow',name:'Titan Hollow',biome:'Ruins',x:61,y:64,danger:6,neighbors:['ashen','crown','starfall'],subsections:['Broken Forum','Titan Gate','Buried Sanctum'],encounters:['infernus','rift-tyrant'],environmentAsset:assetCatalog.ruins},
{id:'starfall',name:'Starfall Reach',biome:'Celestial',x:79,y:53,danger:8,neighbors:['moonfen','hollow','sanctum'],subsections:['Cloud Causeway','Solar Terrace','Starfall Bridge'],encounters:['seraphic','sun'],boss:'sun',environmentAsset:assetCatalog.celestial},
{id:'sanctum',name:'Empyrean Sanctum',biome:'Sacred',x:87,y:30,danger:10,neighbors:['starfall'],subsections:['Outer Halo','Judgement Hall','Empyrean Throne'],encounters:['seraphic','empyrean'],boss:'empyrean',environmentAsset:assetCatalog.celestial}
];

export const items:Item[]=[
{id:'bind-orb',name:'Binding Orb',kind:'capture',power:.28,description:'Attempts to bind a weakened wild creature.'},
{id:'greater-bind',name:'Greater Binding Orb',kind:'capture',power:.46,description:'Improved capture device for elite monsters.'},
{id:'potion',name:'Restoration Tonic',kind:'heal',power:700,description:'Restore 700 HP to one ally.'}
];

export const formationBonuses:FormationBonus[]=[
{name:'Complete Platoon',requires:['Commander','Second','Elite','Soldier','Soldier','Soldier','Soldier','Soldier'],effect:'+10% ATK/DEF to all units.'},
{name:'Celestial Convergence',requires:['Celestial','Seraph','Empyrean'],effect:'+15% magic and status resistance.'},
{name:'Sacred Pair',requires:['Sacred Beast','Sacred Beast'],effect:'Sun/Moon field effects last +50 TU.'}
];
