import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{creatures,zones,items,formationBonuses,Creature,Ability}from'./gameData';import'./style.css';
type Screen='map'|'battle'|'army'|'bestiary'|'inventory';
type Owned={id:string;level:number;xp:number};
const cloneCreature=(id:string)=>creatures.find(c=>c.id===id)!;
function damageFor(c:Creature,a:Ability){if(!a.power)return 0;const scale=a.damageType==='physical'?c.atk:c.magic;return Math.max(1,Math.round(a.power*.35+scale*1.5));}
function App(){
 const[screen,setScreen]=useState<Screen>('map');const[zoneId,setZoneId]=useState('dawnreach');const[subsection,setSubsection]=useState(0);const[owned,setOwned]=useState<Owned[]>([{id:'divine',level:12,xp:0},{id:'nocturne',level:18,xp:0},{id:'rift-drake',level:14,xp:0}]);const[partyIds,setPartyIds]=useState(['divine','nocturne','rift-drake']);const[inventory,setInventory]=useState<Record<string,number>>({'bind-orb':8,'greater-bind':2,potion:5});const[enemyId,setEnemyId]=useState('rift-drake');const[enemyHp,setEnemyHp]=useState(cloneCreature('rift-drake').maxHp);const[partyHp,setPartyHp]=useState<Record<string,number>>({divine:920,nocturne:1050,'rift-drake':1450});const[log,setLog]=useState('The route is quiet.');const[tu,setTu]=useState(0);const[gold,setGold]=useState(500);
 const zone=zones.find(z=>z.id===zoneId)!;const enemy=cloneCreature(enemyId);const party=partyIds.map(cloneCreature);const currentSub=zone.subsections[subsection];
 const discovered=useMemo(()=>new Set(owned.map(o=>o.id)),[owned]);
 function travel(id:string){if(!zone.neighbors.includes(id))return;setZoneId(id);setSubsection(0);setScreen('map');setLog(`Entered ${zones.find(z=>z.id===id)?.name}.`)}
 function moveSub(dir:number){setSubsection(s=>Math.max(0,Math.min(zone.subsections.length-1,s+dir)))}
 function startEncounter(forceBoss=false){const pool=forceBoss&&zone.boss?[zone.boss]:zone.encounters;const id=pool[Math.floor(Math.random()*pool.length)];const c=cloneCreature(id);setEnemyId(id);setEnemyHp(c.maxHp);setTu(0);setLog(`A wild ${c.name} appears in ${currentSub}.`);setScreen('battle')}
 function useAbility(c:Creature,a:Ability){if(!enemyHp||a.tu===0)return;const dmg=damageFor(c,a);setTu(t=>t+a.tu);if(a.target==='foe'||a.target==='all-foes'){setEnemyHp(h=>Math.max(0,h-dmg));setLog(`${c.name} uses ${a.name} for ${dmg} damage.`)}else if(a.target==='all-allies'){setPartyHp(h=>{const n={...h};partyIds.forEach(id=>n[id]=Math.min(cloneCreature(id).maxHp,(n[id]??cloneCreature(id).maxHp)+Math.round(cloneCreature(id).maxHp*.2)));return n});setLog(`${c.name} uses ${a.name}. The army is restored and protected.`)}else{setLog(`${c.name} invokes ${a.name}: ${a.effect}`)}
  setTimeout(()=>enemyTurn(a.tu),180);
 }
 function enemyTurn(cost:number){setEnemyHp(h=>{if(h<=0)return h;const target=partyIds[Math.floor(Math.random()*partyIds.length)];const foe=cloneCreature(enemyId);const dmg=Math.round(foe.atk*.9+zone.danger*24);setPartyHp(p=>({...p,[target]:Math.max(0,(p[target]??cloneCreature(target).maxHp)-dmg)}));setLog(`${foe.name} retaliates for ${dmg} damage.`);return h})}
 function finishVictory(){const reward=enemy.xpYield;setGold(g=>g+zone.danger*18+40);setOwned(o=>o.map(x=>partyIds.includes(x.id)?{...x,xp:x.xp+reward}:x));setLog(`Victory! +${reward} XP and +${zone.danger*18+40} gold.`)}
 function capture(itemId:string){if(enemyHp<=0)return;const it=items.find(i=>i.id===itemId)!;if(!inventory[itemId])return;setInventory(v=>({...v,[itemId]:v[itemId]-1}));const hpFactor=1-enemyHp/enemy.maxHp;const chance=Math.min(.92,it.power+hpFactor*.55+enemy.captureRate);if(Math.random()<chance){if(!discovered.has(enemy.id))setOwned(o=>[...o,{id:enemy.id,level:enemy.level,xp:0}]);setEnemyHp(0);setLog(`${enemy.name} was bound successfully!`)}else setLog(`${enemy.name} resisted the binding attempt.`)}
 function healParty(){if(!inventory.potion)return;setInventory(v=>({...v,potion:v.potion-1}));setPartyHp(Object.fromEntries(partyIds.map(id=>[id,cloneCreature(id).maxHp])));setLog('The party recovered with a Restoration Tonic.')}
 function evolve(id:string){const c=cloneCreature(id);if(!c.next)return;const next=cloneCreature(c.next);const o=owned.find(x=>x.id===id);if(!o||o.level<next.level)return;setOwned(v=>v.map(x=>x.id===id?{id:next.id,level:next.level,xp:0}:x));setPartyIds(v=>v.map(x=>x===id?next.id:x));setPartyHp(v=>{const n={...v};delete n[id];n[next.id]=next.maxHp;return n});setLog(`${c.name} evolved into ${next.name}.`)}
 const formation=formationBonuses.find(f=>f.name==='Celestial Convergence'&&['divine','seraphic','empyrean'].every(id=>partyIds.includes(id)));
 return <main><header><div><b>DIB II</b><span> ISLES OF ASCENDANCE</span></div><nav>{(['map','army','bestiary','inventory']as Screen[]).map(x=><button key={x} onClick={()=>setScreen(x)} className={screen===x?'on':''}>{x}</button>)}</nav><div className="gold">◈ {gold}</div></header>
 {screen==='map'&&<section className="layout"><aside><h2>{zone.name}</h2><p>{zone.biome} · Danger {zone.danger}</p><div className="subcard"><span>LOCAL SUBSECTION</span><strong>{currentSub}</strong><div><button disabled={subsection===0} onClick={()=>moveSub(-1)}>←</button><b>{subsection+1}/{zone.subsections.length}</b><button disabled={subsection===zone.subsections.length-1} onClick={()=>moveSub(1)}>→</button></div></div><h3>CONNECTED REGIONS</h3>{zone.neighbors.map(n=>{const z=zones.find(x=>x.id===n)!;return <button key={n} className="route" onClick={()=>travel(n)}>{z.name}<small>{z.biome}</small></button>})}<button className="encounter" onClick={()=>startEncounter(false)}>SEARCH THIS SUBSECTION</button>{zone.boss&&subsection===zone.subsections.length-1&&<button className="boss" onClick={()=>startEncounter(true)}>CHALLENGE REGION BOSS</button>}</aside><div className="world" style={{backgroundImage:`linear-gradient(#05090bbd,#05090bbd),url(${zone.environmentAsset})`}}><div className="worldmap" style={{backgroundImage:`url(/assets/world/world-map.png)`}}></div>{zones.map(z=><button key={z.id} title={z.name} className={'node '+(z.id===zone.id?'active':'')} style={{left:z.x+'%',top:z.y+'%'}} onClick={()=>zone.neighbors.includes(z.id)&&travel(z.id)}><i></i><span>{z.name}</span></button>)}<div className="viewport"><strong>LOCAL VIEW</strong><h2>{currentSub}</h2><p>You explore only this subsection. The complete island exists as the travel layer beneath it.</p></div></div></section>}
 {screen==='battle'&&<section className="battle"><div className="enemy"><img src={enemy.asset} onError={e=>(e.currentTarget.style.display='none')} /><div><h2>{enemy.name} <small>Lv. {enemy.level}</small></h2><p>{enemy.role} · {enemy.affinity}</p><div className="bar"><i style={{width:(enemyHp/enemy.maxHp*100)+'%'}}></i></div><p>{enemyHp} / {enemy.maxHp} HP · Timeline {tu} TU</p></div></div><div className="battlelog">{enemyHp?log:<><b>{log.includes('bound')?log:'Victory — the encounter is won.'}</b>{!log.includes('bound')&&<button onClick={finishVictory}>CLAIM REWARDS</button>}</>}</div><div className="party">{party.map(c=><article key={c.id}><img className="portraitImg" src={c.asset}/><h3>{c.name} <small>Lv.{c.level}</small></h3><div className="bar ally"><i style={{width:((partyHp[c.id]??c.maxHp)/c.maxHp*100)+'%'}}></i></div><p>{partyHp[c.id]??c.maxHp}/{c.maxHp} HP</p>{c.abilities.map(a=><button key={a.name} disabled={!enemyHp||a.tu===0||(partyHp[c.id]??0)<=0} onClick={()=>useAbility(c,a)}>{a.name}<small>{a.tu?`${a.tu} TU`:'PASSIVE'}</small></button>)}</article>)}</div><div className="battletools"><button onClick={()=>capture('bind-orb')}>Binding Orb ×{inventory['bind-orb']||0}</button><button onClick={()=>capture('greater-bind')}>Greater Orb ×{inventory['greater-bind']||0}</button><button onClick={healParty}>Tonic ×{inventory.potion||0}</button><button onClick={()=>setScreen('map')}>RETREAT</button></div></section>}
 {screen==='army'&&<section className="cards"><h1>ARMY</h1>{formation&&<div className="formation">FORMATION ACTIVE: {formation.name} — {formation.effect}</div>}{owned.map(o=>{const c=cloneCreature(o.id);const next=c.next&&cloneCreature(c.next);return <article key={c.id}><img className="cardArt" src={c.asset}/><h2>{c.name}</h2><p>{c.role} · {c.affinity}</p><b>Lv. {o.level}</b><p>XP {o.xp} · HP {c.hp}<br/>ATK {c.atk} · DEF {c.def}<br/>MAG {c.magic} · SPD {c.speed}</p><button className={partyIds.includes(c.id)?'selected':''} onClick={()=>{if(partyIds.includes(c.id))setPartyIds(v=>v.filter(x=>x!==c.id));else if(partyIds.length<3)setPartyIds(v=>[...v,c.id])}}>{partyIds.includes(c.id)?'IN ACTIVE PARTY':'ADD TO PARTY'}</button>{next&&<button disabled={o.level<next.level} onClick={()=>evolve(c.id)}>EVOLVE → {next.name} {o.level<next.level?`(Lv.${next.level})`:''}</button>}</article>})}</section>}
 {screen==='bestiary'&&<section className="cards"><h1>BESTIARY</h1>{creatures.map(c=><article key={c.id} className={!discovered.has(c.id)?'locked':''}><img className="cardArt" src={c.asset}/><h2>{discovered.has(c.id)?c.name:'Unknown Creature'}</h2><p>Stage {c.stage} · {c.affinity}</p><b>{c.role}</b>{c.next&&<p>Evolution → {cloneCreature(c.next).name}</p>}<details><summary>Abilities</summary>{c.abilities.map(a=><p key={a.name}><strong>{a.name}</strong> · {a.tu||'Passive'} TU<br/>{a.effect}</p>)}</details></article>)}</section>}
 {screen==='inventory'&&<section className="cards"><h1>INVENTORY</h1>{items.map(i=><article key={i.id}><div className="sigil">◇</div><h2>{i.name}</h2><b>× {inventory[i.id]||0}</b><p>{i.description}</p></article>)}</section>}
 <footer>{log} · {zones.length} regions · {zones.reduce((n,z)=>n+z.subsections.length,0)} playable subsections · Data-driven evolution graph</footer></main>}
createRoot(document.getElementById('root')!).render(<App/>);